version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/vacation-system
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html/vacation-system
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=vacation-system
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=vacation-system
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
